import type { ModelInfo } from "../model.js"

export type GptChatByModelId = keyof typeof gptChatByModels

export const gptChatByDefaultModelId: GptChatByModelId = "mimo/free"

const GTP_CHAT_BY_TAKE_PROFIT_USD = 1.15;

export const gptChatByModels = {
	"mimo/free": {
		maxTokens: 16_384,
		contextWindow: 150_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: false,
		inputPrice: 0,
		outputPrice: 0,
		description: `Mimo v2 Flash.`,
		isFree: true,
	},
	"openai/gpt-oss-120b": {
		maxTokens: 16_384,
		contextWindow: 128_072,
		supportsImages: false,
		supportsPromptCache: false,
		supportsNativeTools: true,
		inputPrice: 0.04 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 0.2 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		cacheWritesPrice: 0,
		cacheReadsPrice: 0,
		description: "Extremely capable general-purpose LLM with strong, controllable reasoning capabilities",
	},
	"qwen/coder-480B": {
		maxTokens: 32768,
		contextWindow: 262144,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		inputPrice: 0.22 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Qwen Coder - High-performance coding model with 1M context window for large codebases.`,
	},
	"qwen/plus-3.5": {
		maxTokens: 65_000,
		contextWindow: 262_000,
		supportsImages: true,
		supportsPromptCache: false,
		supportsNativeTools: true,
		inputPrice: 0.4 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 2.4 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `The Qwen3.5 native vision-language series Plus models are built on a hybrid architecture that integrates linear attention mechanisms with sparse mixture-of-experts models, achieving higher inference efficiency.`,
	},
	"qwen/qwen3.5-397B": {
		maxTokens: 65_000,
		contextWindow: 262_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsNativeTools: true,
		inputPrice: 0.6 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 3.6 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `The Qwen3.5 397B native vision-language series Plus models are built on a hybrid architecture that integrates linear attention mechanisms with sparse mixture-of-experts models, achieving higher inference efficiency.`,
	},
	"google/gemini-3-flash": {
		maxTokens: 65_536,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		supportsPromptCache: true,
		inputPrice: 0.5 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 3 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Google: Gemini 3 Flash Preview.`,
	},
	"google/gemini-3.1-flash-lite-preview": {
		maxTokens: 65_536,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		supportsPromptCache: true,
		supportsReasoningEffort: ["minimal", "low", "medium", "high"],
		reasoningEffort: "medium",
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0.25 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 1.5 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Gemini 3.1 Flash Lite Preview.`,
	},
	"google/gemini-3-pro": {
		maxTokens: 65_536,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "high"],
		reasoningEffort: "low",
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 4.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 18.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		tiers: [
			{
				contextWindow: 200_000,
				inputPrice: 2.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
				outputPrice: 12.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
			},
			{
				contextWindow: Infinity,
				inputPrice: 4.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
				outputPrice: 18.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
			},
		],
	},
	"google/gemini-3.1-pro": {
		maxTokens: 65_536,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "high"],
		reasoningEffort: "low",
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 4.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 18.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		tiers: [
			{
				contextWindow: 200_000,
				inputPrice: 2.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
				outputPrice: 12.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
			},
			{
				contextWindow: Infinity,
				inputPrice: 4.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
				outputPrice: 18.0 * GTP_CHAT_BY_TAKE_PROFIT_USD,
			},
		],
	},
	"deepseek/deepseek-v3.2": {
		maxTokens: 32768,
		contextWindow: 163_840,
		supportsImages: false,
		supportsPromptCache: false,
		supportsNativeTools: true,
		inputPrice: 0.28 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 0.45 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `deepseek 3.2`,
	},
	"minimax/m2.5": {
		maxTokens: 180_000,
		contextWindow: 180_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: true,
		includedTools: ["search_and_replace"],
		excludedTools: ["apply_diff"],
		inputPrice: 0.12 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 0.48 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `MiniMax M2.5`,
	},
	"inception/mercury-2": {
		maxTokens: 50_000,
		contextWindow: 120_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: true,
		inputPrice: 0.25 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 0.75 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Mercury 2 is an extremely fast reasoning LLM, and the first reasoning diffusion LLM (dLLM).`,
	},
	"kwaipilot/kat-coder-pro": {
		maxTokens: 32768,
		contextWindow: 256_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: true,
		inputPrice: 0.3 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 1.2 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `KAT Coder PRO.`,
	},
	"moonshotai/kimi-k2.5": {
		maxTokens: 16_384,
		contextWindow: 262_144,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningBinary: true,
		supportsAdaptiveThinking: true,
		preserveReasoning: true,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		inputPrice: 0.6 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 2.85 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		cacheReadsPrice: 0.1, // $0.10 per million tokens (cache hit)
		supportsTemperature: false,
		defaultTemperature: 0.6,
		description: "Kimi K2.5 is the latest generation of Moonshot AI's Kimi series, featuring improved reasoning capabilities and enhanced performance across diverse tasks.",
	},
	"z-ai/glm-4.7-flash": {
		maxTokens: 65_000,
		contextWindow: 200_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: true,
		inputPrice: 0.06 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 0.4 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `As a 30B-class SOTA model, GLM-4.7-Flash offers a new option that balances performance and efficiency.`,
	},
	"z-ai/glm-4.7": {
		maxTokens: 65_000,
		contextWindow: 200_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: true,
		inputPrice: 0.38 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 1.98 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `GLM-4.7 is Z.ai’s latest flagship model, featuring upgrades in two key areas: enhanced programming capabilities and more stable multi-step reasoning/execution.`,
	},
	"z-ai/glm-5": {
		maxTokens: 65_000,
		contextWindow: 200_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: true,
		inputPrice: 0.8 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 2.56 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `GLM-5 is Z.ai’s flagship open-source foundation model engineered for complex systems design and long-horizon agent workflows. `,
	},
} as const satisfies Record<string, ModelInfo>

export const GPT_CHAT_BY_DEFAULT_TEMPERATURE = 0.6
